/**
 * Recognising an HTML page served where a machine-readable file was asked for.
 *
 * A 200 is no promise that the body is what the URL names. Single-page apps
 * and many CMS themes answer every unknown path with their homepage or a
 * styled "not found" page (a soft 404), and bot protection answers with a
 * challenge page. Asked for /wp-sitemap.xml, such a host returns 200 and
 * HTML. Parsing that as XML yields nothing and reads as "a broken sitemap".
 * It is actually "no sitemap here", or "we were blocked", and each of those
 * wants different handling.
 */

export type HtmlResponseKind = 'bot-challenge' | 'html-page';

/** How far into the body to look. The tell is always at the top. */
const SNIFF_BYTES = 4096;

/**
 * Pages from the common bot-protection vendors. Matched on text those pages
 * are built from, so a normal page that happens to mention a captcha deep in
 * its body is not caught: only the first few KB are examined.
 */
const CHALLENGE_MARKERS = [
  /<title>\s*just a moment\.\.\.\s*<\/title>/i, // Cloudflare
  /<title>\s*attention required!?\s*\|\s*cloudflare/i,
  /cf-chl-|cf_chl_opt|challenge-platform/i,
  /<title>\s*access denied\s*<\/title>/i, // Akamai, generic WAFs
  /sucuri website firewall/i,
  /ddos-guard/i,
  /<title>[^<]*(captcha|are you (a )?human|bot verification)[^<]*<\/title>/i,
];

/** A root element that makes the document a sitemap whatever it was served as. */
const SITEMAP_ROOT = /<(?:[\w-]+:)?(?:urlset|sitemapindex)[\s>]/i;

function head(body: string): string {
  return (
    body
      .slice(0, SNIFF_BYTES)
      .replace(/^\uFEFF/, '')
      // Leading comments are common in themes ("<!-- generated by ... -->").
      .replace(/^(\s*<!--[\s\S]*?-->)+/, '')
      .trimStart()
  );
}

/**
 * Whether the body is an HTML document rather than the XML or text asked for.
 *
 * The body decides, not the Content-Type header: plenty of hosts serve a
 * valid sitemap as text/html, and plenty serve their HTML homepage as
 * application/xml. The header only settles a body that is ambiguous by itself.
 */
export function isHtmlResponse(body: string | undefined, contentType?: string): boolean {
  if (!body) return false;
  const top = head(body);
  if (SITEMAP_ROOT.test(top)) return false;
  if (/^<!doctype\s+html/i.test(top) || /^<(html|head|body)[\s>]/i.test(top)) return true;
  // XHTML with an XML prolog.
  if (/^<\?xml/i.test(top) && /<html[\s>]/i.test(top)) return true;
  if (contentType && /\b(text\/html|application\/xhtml\+xml)\b/i.test(contentType)) {
    return /<(html|head|body|div|script|meta)[\s>]/i.test(top);
  }
  return false;
}

/** Given an HTML response, whether it is a bot-protection challenge or an ordinary page. */
export function classifyHtmlResponse(body: string): HtmlResponseKind {
  const top = body.slice(0, SNIFF_BYTES);
  return CHALLENGE_MARKERS.some((marker) => marker.test(top)) ? 'bot-challenge' : 'html-page';
}

/** A short, plain explanation of an HTML response, for evidence and logs. */
export function describeHtmlResponse(url: string, body: string): string {
  return classifyHtmlResponse(body) === 'bot-challenge'
    ? `${url} returned 200 with a bot-protection challenge page instead of the file, so the crawler was blocked from reading it.`
    : `${url} returned 200 with an HTML page instead of XML. The site most likely answers unknown paths with a page ` +
        '(a soft 404 or a catch-all route), so there is no sitemap at this address.';
}
