import type { CalendarItem, CompetitorContent } from './api-client';

/**
 * Utility functions for 1-click exports: CSV, Markdown, Notion, and Text packets.
 */

export function downloadFile(content: string, filename: string, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportCalendarToCsv(items: CalendarItem[], projectName = 'growthx-editorial-calendar') {
  const headers = ['Title', 'Platform', 'Content Type', 'Content Pillar', 'Status', 'Hook', 'Scheduled Date', 'Caption', 'Hashtags'];
  
  const rows = items.map((item) => [
    `"${(item.title || '').replace(/"/g, '""')}"`,
    `"${item.platform || ''}"`,
    `"${item.contentType || ''}"`,
    `"${item.contentPillar || ''}"`,
    `"${item.status || 'DRAFT'}"`,
    `"${(item.hook || '').replace(/"/g, '""')}"`,
    `"${item.scheduledFor ? new Date(item.scheduledFor).toISOString().split('T')[0] : ''}"`,
    `"${(item.caption || '').replace(/"/g, '""')}"`,
    `"${(item.hashtags || []).join(' ')}"`,
  ]);

  const csvContent = [headers.join(','), ...rows.map((r) => r.join(','))].join('\n');
  const dateStr = new Date().toISOString().split('T')[0];
  downloadFile(csvContent, `${projectName}-${dateStr}.csv`, 'text/csv');
}

export function exportCalendarToMarkdown(items: CalendarItem[], projectName = 'Editorial Calendar') {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  
  let md = `# ${projectName} — Content Production Plan\n`;
  md += `*Generated by GrowthX AI on ${dateStr}*\n\n`;
  md += `## Calendar Summary\n`;
  md += `- **Total Planned Assets**: ${items.length}\n`;
  md += `- **Approved / Scheduled**: ${items.filter((i) => ['APPROVED', 'SCHEDULED', 'PUBLISHED'].includes(i.status)).length}\n`;
  md += `- **In Draft**: ${items.filter((i) => i.status === 'DRAFT').length}\n\n`;
  
  md += `## Production Schedule & Briefs\n\n`;

  items.forEach((item, idx) => {
    md += `### ${idx + 1}. [${item.platform}] ${item.title}\n`;
    md += `- **Status**: \`${item.status}\`\n`;
    md += `- **Format**: ${item.contentType} (${item.contentPillar || 'General'})\n`;
    if (item.scheduledFor) {
      md += `- **Scheduled Date**: ${new Date(item.scheduledFor).toLocaleString()}\n`;
    }
    if (item.hook) {
      md += `- **Opening Hook**: > *"${item.hook}"*\n`;
    }
    if (item.caption) {
      md += `\n**Caption / Teleprompter Script**:\n\`\`\`text\n${item.caption}\n\`\`\`\n`;
    }
    if (item.hashtags && item.hashtags.length > 0) {
      md += `\n**Tags**: ${item.hashtags.map((h) => `#${h.replace(/^#/, '')}`).join(' ')}\n`;
    }
    md += `\n---\n\n`;
  });

  const fileSlug = projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  downloadFile(md, `${fileSlug}-plan.md`, 'text/markdown');
}

export function exportCompetitorDossier(competitorName: string, domain: string, pages: any[], videos: CompetitorContent[], gaps: any[]) {
  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  
  let md = `# Competitor Intelligence Dossier: ${competitorName} (${domain})\n`;
  md += `*Analyzed by GrowthX AI Engine on ${dateStr}*\n\n`;
  
  md += `## 1. Domain & Catalog Architecture\n`;
  md += `- **Total Indexed Pages**: ${pages.length}\n`;
  md += `- **Identified Products**: ${pages.filter((p) => p.pageType === 'PRODUCT').length}\n`;
  md += `- **Identified Services**: ${pages.filter((p) => p.pageType === 'SERVICE').length}\n\n`;
  
  md += `### Discovered Key Pages\n`;
  md += `| Page URL | Type | Word Count | Status |\n| :--- | :--- | :--- | :--- |\n`;
  pages.slice(0, 15).forEach((p) => {
    md += `| [${p.title || p.url}](${p.url}) | \`${p.pageType}\` | ${p.wordCount || 0} words | ${p.statusCode || 200} |\n`;
  });
  md += `\n`;

  if (videos.length > 0) {
    md += `## 2. Social Video & Hook Formula Teardowns\n\n`;
    videos.forEach((v, idx) => {
      md += `### Video ${idx + 1}: ${v.title || 'Competitor Reel'}\n`;
      md += `- **Platform**: ${v.platform} (${v.contentType})\n`;
      md += `- **Engagement**: ${(v.viewsCount || 0).toLocaleString()} views · ${(v.likesCount || 0).toLocaleString()} likes\n`;
      if (v.hookAnalysis?.hook) {
        md += `- **Hook Formula**: *"${v.hookAnalysis.hook}"* (\`${v.hookAnalysis.hookType || 'HOOK'}\`)\n`;
      }
      if (v.transcript) {
        md += `\n**Audio Transcript**:\n> ${v.transcript}\n`;
      }
      if (v.whyItWorks) {
        md += `\n**Why It Converts**: ${v.whyItWorks}\n`;
      }
      md += `\n---\n\n`;
    });
  }

  if (gaps.length > 0) {
    md += `## 3. Recommended Growth Opportunities (Catalog & Content Gaps)\n\n`;
    gaps.forEach((g: any, idx: number) => {
      md += `### ${idx + 1}. ${g.topic || g.title || 'Identified Gap'}\n`;
      md += `- **Opportunity Score**: ${g.opportunityScore || 85}/100\n`;
      md += `- **Search Intent**: ${g.searchIntent || 'Commercial'}\n`;
      if (g.angle) md += `- **Strategic Angle**: ${g.angle}\n`;
      md += `\n`;
    });
  }

  const fileSlug = domain.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
  downloadFile(md, `${fileSlug}-competitor-dossier.md`, 'text/markdown');
}
