import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "The terms under which GrowthX AI SEO is provided: what you may connect, what the product does on your behalf, and the limits of what it guarantees.",
};

const LAST_UPDATED = "9 September 2026";

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="mt-10 scroll-mt-24">
      <h2 className="text-lg font-bold tracking-tight text-slate-900">{title}</h2>
      <div className="mt-3 space-y-3 text-sm leading-relaxed text-slate-600">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <article>
      <h1 className="text-2xl font-bold tracking-tight text-slate-900">Terms of Service</h1>
      <p className="mt-2 text-sm text-slate-500">Last updated {LAST_UPDATED}</p>

      <p className="mt-6 text-sm leading-relaxed text-slate-600">
        These terms govern your use of GrowthX AI SEO. By creating an account or connecting a
        service to it, you agree to them.
      </p>

      <Section id="service" title="What the service does">
        <p>
          GrowthX crawls websites you nominate, reads data from marketing accounts you connect, and
          produces analysis and recommendations about search visibility. It is an analysis tool. It
          does not guarantee any ranking, traffic level or commercial outcome, and search engines
          give no such guarantees to anyone who claims otherwise.
        </p>
      </Section>

      <Section id="accounts" title="Your account">
        <p>
          You are responsible for keeping your credentials secure and for activity under your
          account. Tell us promptly if you believe it has been accessed by someone else.
        </p>
      </Section>

      <Section id="authority" title="What you may connect">
        <p>
          You may only add websites and connect accounts that you own or are authorised to manage on
          the owner&apos;s behalf. Connecting a client&apos;s Google Business Profile, Search Console
          or Analytics account means you are confirming you have their permission to do so. You are
          responsible for having that permission.
        </p>
      </Section>

      <Section id="changes-to-profiles" title="Changes made on your behalf">
        <p>
          Where the product can write back to a connected service — for example proposing a change to
          a Google Business Profile — it does so only after you approve that specific change. You
          remain responsible for reviewing a proposal before approving it, and for the accuracy of
          what is published to a profile you control.
        </p>
      </Section>

      <Section id="ai" title="Automated recommendations">
        <p>
          Recommendations are generated by large language models and can be wrong, incomplete or out
          of date. Treat them as suggestions to review, not instructions to follow blindly. You are
          responsible for deciding what to act on.
        </p>
      </Section>

      <Section id="acceptable" title="Acceptable use">
        <p>
          Do not use the service to crawl sites you have no right to crawl, to circumvent a
          site&apos;s access controls, to attempt to overload any third-party API, or to break any
          law or the terms of a service you have connected. We may suspend an account that does.
        </p>
      </Section>

      <Section id="third-party" title="Third-party services">
        <p>
          The product depends on services we do not control, including Google&apos;s APIs and the AI
          providers named in our Privacy Policy. Those services can change, impose quotas, withdraw
          access or fail. Where a data source is unavailable, the product reports that rather than
          substituting an estimate — but we cannot guarantee continuous availability of any feature
          that depends on a third party.
        </p>
      </Section>

      <Section id="availability" title="Availability">
        <p>
          We aim for the service to be available and correct, but we provide it &ldquo;as is&rdquo;
          without warranties. To the extent the law permits, we are not liable for indirect or
          consequential loss, including lost revenue or lost rankings.
        </p>
      </Section>

      <Section id="termination" title="Ending the arrangement">
        <p>
          You may stop using the service and delete your account at any time. We may suspend or end
          access for a serious or repeated breach of these terms. On termination we remove your data
          as described in the Privacy Policy.
        </p>
      </Section>

      <Section id="changes" title="Changes to these terms">
        <p>
          We may update these terms. Material changes will be notified to account holders, and the
          date above will change.
        </p>
      </Section>

      <Section id="contact" title="Contact">
        <p>Questions about these terms can be sent to the address on our website.</p>
      </Section>
    </article>
  );
}
